### ISSUE TITLE
update messageformat dependency

### ISSUE THREAD

**Issue by rodneyrehm** [asciidisco/require-po-plugin#1]
```
require-po-plugin#0.2.0
 -> messageformat#0.2.1 (latest is 0.3.0-1)
```

**Comment by asciidisco** [comment]
Going to investigate this.
0.2.1 -> 0.3.0 has some potential for breaking the plugin (as we did some dark voodoo magic for making builds with plural values work)

**Comment by asciidisco** [comment]
Done with 0.2.5
