### ISSUE TITLE
pluralization not working for "none"

### ISSUE THREAD

**Issue by rodneyrehm** [asciidisco/require-po-plugin#4]
Open [`example/index.html`](https://github.com/asciidisco/require-po-plugin/blob/master/example/index.html) to see that the pluralization doesn't work for "none". This worked fine in v0.2.3 (we recently upgraded to v0.2.6 because of #2). The problem was introduced somewhere [between 0.2.3 and 0.2.5](https://github.com/asciidisco/require-po-plugin/compare/0.2.3...0.2.5).

---

The message

```
"{items, plural, none{No devices found} one{found 1 device} other{found {items} devices}}"
```

produces the following output

```
{items: 0}: "found 0 devices"
{items: 1}: "found 1 device"
{items: 5}: "found 5 devices"
```

but for zero devices it should've been `No devices found`.

---

Neither the `Plural-Forms` header in `example/i18n/en_GB/labels.po` nor the function in `example/i18n/en_GB/locale.js` seem to be respected.

**Comment by asciidisco** [comment]
I´ll investigate this within the next days.

**Comment by rodneyrehm** [comment]
The problem does not show up with messageformat 0.2.1 and it throws a proper error with messageformat 1.0.2.
